"""PostgreSQL connection factory and schema initialiser for V3 permanent storage.

All permanent V3 data lives here:
  v3_signal_id_seq   — sequence counter (atomic, locked)
  v3_candidates      — every signal generated by any strategy
  v3_push_queue      — Telegram dispatch queue
  v3_paper_orders    — simulation trade lifecycle
  v3_order_events    — immutable audit log
  v3_feature_store   — raw factors per signal (AI training data)

SQLite keeps only: klines, universe, runner caches.
"""
from __future__ import annotations

import logging
import os
import time

import psycopg2
import psycopg2.extras

log = logging.getLogger(__name__)

_PG_DDL = """
CREATE TABLE IF NOT EXISTS v3_signal_id_seq (
    prefix   TEXT    NOT NULL,
    date     TEXT    NOT NULL,
    next_seq INTEGER NOT NULL DEFAULT 1,
    PRIMARY KEY (prefix, date)
);

CREATE TABLE IF NOT EXISTS v3_candidates (
    signal_id      TEXT PRIMARY KEY,
    strategy_id    TEXT NOT NULL,
    created_at     TEXT NOT NULL,
    symbol         TEXT NOT NULL,
    direction      TEXT NOT NULL,
    entry          TEXT NOT NULL,
    sl             TEXT NOT NULL,
    tp1            TEXT NOT NULL,
    tp2            TEXT,
    rr             TEXT NOT NULL,
    confidence     REAL,
    stop_pct       REAL,
    change_24h     REAL,
    quote_volume   REAL,
    volume_ratio   REAL,
    atr            REAL,
    ema20          REAL,
    ema60          REAL,
    market_regime  TEXT,
    reason         TEXT,
    status         TEXT NOT NULL DEFAULT 'PENDING',
    repeat_count   INTEGER NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_pg_cand_symbol_dir
    ON v3_candidates(symbol, direction, created_at);
CREATE INDEX IF NOT EXISTS idx_pg_cand_strategy
    ON v3_candidates(strategy_id, created_at);
CREATE INDEX IF NOT EXISTS idx_pg_cand_status
    ON v3_candidates(status);

CREATE TABLE IF NOT EXISTS v3_push_queue (
    push_id             TEXT PRIMARY KEY,
    signal_id           TEXT NOT NULL,
    strategy_id         TEXT NOT NULL,
    telegram_message_id TEXT,
    pushed_at           TEXT,
    push_status         TEXT NOT NULL DEFAULT 'QUEUED',
    retry_count         INTEGER NOT NULL DEFAULT 0,
    cooldown_until      TEXT,
    created_at          TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_pg_push_signal
    ON v3_push_queue(signal_id);
CREATE INDEX IF NOT EXISTS idx_pg_push_status
    ON v3_push_queue(push_status, cooldown_until);

CREATE TABLE IF NOT EXISTS v3_paper_orders (
    order_id      TEXT PRIMARY KEY,
    signal_id     TEXT NOT NULL,
    strategy_id   TEXT NOT NULL,
    symbol        TEXT NOT NULL,
    direction     TEXT NOT NULL,
    entry         TEXT NOT NULL,
    stop_loss     TEXT NOT NULL,
    tp1           TEXT NOT NULL,
    tp2           TEXT NOT NULL,
    rr            TEXT NOT NULL,
    status        TEXT NOT NULL DEFAULT 'OPEN',
    result        TEXT,
    created_at    TEXT NOT NULL,
    filled_at     TEXT,
    closed_at     TEXT,
    expires_at    TEXT NOT NULL,
    pnl_pct       TEXT,
    rr_realized   TEXT,
    pushed        INTEGER NOT NULL DEFAULT 1,
    metadata_json TEXT NOT NULL DEFAULT '{}'
);
CREATE INDEX IF NOT EXISTS idx_pg_orders_strategy
    ON v3_paper_orders(strategy_id, status);
CREATE INDEX IF NOT EXISTS idx_pg_orders_symbol
    ON v3_paper_orders(symbol, direction, status);
CREATE INDEX IF NOT EXISTS idx_pg_orders_signal
    ON v3_paper_orders(signal_id);
CREATE INDEX IF NOT EXISTS idx_pg_orders_closed
    ON v3_paper_orders(closed_at);

CREATE TABLE IF NOT EXISTS v3_order_events (
    event_id      TEXT PRIMARY KEY,
    order_id      TEXT NOT NULL,
    signal_id     TEXT NOT NULL,
    event_type    TEXT NOT NULL,
    old_status    TEXT,
    new_status    TEXT,
    candle_high   TEXT,
    candle_low    TEXT,
    triggered_at  TEXT NOT NULL,
    metadata_json TEXT NOT NULL DEFAULT '{}'
);
CREATE INDEX IF NOT EXISTS idx_pg_events_order
    ON v3_order_events(order_id);

CREATE TABLE IF NOT EXISTS v3_feature_store (
    signal_id     TEXT PRIMARY KEY,
    strategy_id   TEXT NOT NULL,
    created_at    TEXT NOT NULL,
    features_json TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_pg_feat_strategy
    ON v3_feature_store(strategy_id, created_at);

CREATE TABLE IF NOT EXISTS live_orders (
    live_order_id   TEXT PRIMARY KEY,
    signal_id       TEXT NOT NULL,
    symbol          TEXT NOT NULL,
    side            TEXT NOT NULL,
    direction       TEXT NOT NULL,
    entry           TEXT NOT NULL,
    sl              TEXT NOT NULL,
    tp              TEXT NOT NULL,
    notional        TEXT NOT NULL,
    leverage        INTEGER NOT NULL DEFAULT 10,
    quantity        TEXT NOT NULL,
    status          TEXT NOT NULL DEFAULT 'PENDING',
    entry_order_id  TEXT,
    sl_order_id     TEXT,
    tp_order_id     TEXT,
    created_at      TEXT NOT NULL,
    updated_at      TEXT NOT NULL,
    reject_reason   TEXT
);
CREATE INDEX IF NOT EXISTS idx_live_orders_status
    ON live_orders(status);
CREATE INDEX IF NOT EXISTS idx_live_orders_symbol
    ON live_orders(symbol, status);
CREATE INDEX IF NOT EXISTS idx_live_orders_signal
    ON live_orders(signal_id);

-- strategy_id: distinguishes V3 (hotlist_momentum_v3) vs V66 (hotlist_v66) live
-- orders so each strategy's conflict resolution only sees its own orders and
-- the two never falsely collide on the same symbol. Backfilled to the V3
-- strategy id for any pre-existing rows (V3 was the only live strategy before).
ALTER TABLE live_orders ADD COLUMN IF NOT EXISTS strategy_id TEXT NOT NULL DEFAULT 'hotlist_momentum_v3';
CREATE INDEX IF NOT EXISTS idx_live_orders_strategy
    ON live_orders(strategy_id, symbol, status);

CREATE TABLE IF NOT EXISTS v66_watchlist (
    symbol             TEXT PRIMARY KEY,
    source             TEXT NOT NULL,
    first_seen_at      TEXT NOT NULL,
    last_seen_at       TEXT NOT NULL,
    expires_at         TEXT NOT NULL,
    observation_count  INTEGER NOT NULL,
    last_rank          INTEGER NOT NULL,
    status             TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_v66_watchlist_status
    ON v66_watchlist(status, expires_at);

CREATE TABLE IF NOT EXISTS live_events (
    event_id        TEXT PRIMARY KEY,
    live_order_id   TEXT NOT NULL,
    signal_id       TEXT NOT NULL,
    event_type      TEXT NOT NULL,
    details_json    TEXT NOT NULL DEFAULT '{}',
    created_at      TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_live_events_order
    ON live_events(live_order_id);
CREATE INDEX IF NOT EXISTS idx_live_events_type
    ON live_events(event_type, created_at);

-- Conflict-management fields — populated when a new signal collides with an
-- existing live order/position for the same symbol (see v3/live/order_manager.py)
ALTER TABLE live_events ADD COLUMN IF NOT EXISTS old_signal_id TEXT;
ALTER TABLE live_events ADD COLUMN IF NOT EXISTS new_signal_id TEXT;
ALTER TABLE live_events ADD COLUMN IF NOT EXISTS symbol        TEXT;
ALTER TABLE live_events ADD COLUMN IF NOT EXISTS old_side      TEXT;
ALTER TABLE live_events ADD COLUMN IF NOT EXISTS new_side      TEXT;
ALTER TABLE live_events ADD COLUMN IF NOT EXISTS old_entry     TEXT;
ALTER TABLE live_events ADD COLUMN IF NOT EXISTS new_entry     TEXT;
ALTER TABLE live_events ADD COLUMN IF NOT EXISTS action        TEXT;
ALTER TABLE live_events ADD COLUMN IF NOT EXISTS reason        TEXT;

-- live_orders.status also accepts (beyond the original set):
--   REPLACED, CANCELED_EXPIRED, CANCELED_CONFLICT, IGNORED_DUPLICATE,
--   IGNORED_WORSE_ENTRY, DIRECTION_CONFLICT, POSITION_EXISTS_SAME_SIDE,
--   POSITION_EXISTS_OPPOSITE_SIDE
-- (status stays a free-text column — no CHECK constraint — to avoid migration
-- pain; validity is enforced in Python via LiveOrderStatus).

CREATE TABLE IF NOT EXISTS v3_scan_debug (
    strategy_id          TEXT PRIMARY KEY,
    created_at           TEXT NOT NULL,
    pool_size            INTEGER NOT NULL,
    computed_count       INTEGER NOT NULL,
    live_eligible_count  INTEGER NOT NULL,
    top10_json           TEXT NOT NULL DEFAULT '[]',
    crowded_out_json     TEXT NOT NULL DEFAULT '[]'
);

-- v3_live_paper_comparison: append-only side-by-side record of each paper
-- settlement result vs. the real live_orders status at that moment. Written
-- once per settlement when a live mirror exists — purely for future offline
-- analysis of paper-vs-live divergence; never read by PerformanceCalculator
-- and never mutates existing stats (per user decision: paper stats stay
-- self-contained / independently optimized, this table is just a diff log).
CREATE TABLE IF NOT EXISTS v3_live_paper_comparison (
    id              BIGSERIAL PRIMARY KEY,
    signal_id       TEXT NOT NULL,
    strategy_id     TEXT NOT NULL,
    symbol          TEXT NOT NULL,
    paper_result    TEXT NOT NULL,
    paper_closed_at TEXT NOT NULL,
    live_status     TEXT,
    live_closed_at  TEXT,
    match           BOOLEAN NOT NULL,
    created_at      TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_live_paper_cmp_signal
    ON v3_live_paper_comparison(signal_id);
CREATE INDEX IF NOT EXISTS idx_live_paper_cmp_strategy
    ON v3_live_paper_comparison(strategy_id, created_at);

-- v3_runtime_settings: live-adjustable dedup/position-limit overrides, set via
-- Telegram /setlimit command. NULL column = "no override, use hardcoded default".
CREATE TABLE IF NOT EXISTS v3_runtime_settings (
    strategy_id      TEXT PRIMARY KEY,
    dedup_hours      INTEGER,
    max_open_orders  INTEGER,
    updated_at       TEXT,
    updated_by       TEXT
);

-- live_enabled: per-strategy DB-backed live-trading switch, controlled via the
-- Telegram /livemode command. Combined with the global LIVE_TRADING_ENABLED
-- env var as a kill switch (both must be true for real orders to be placed).
-- notional_usdt: per-strategy live position size override (NULL = hardcoded default).
ALTER TABLE v3_runtime_settings ADD COLUMN IF NOT EXISTS live_enabled  BOOLEAN;
ALTER TABLE v3_runtime_settings ADD COLUMN IF NOT EXISTS notional_usdt NUMERIC;

-- ── Classic Shadow comparison records ───────────────────────────────────────
-- Stores shadow strategy evaluation result for every K1/K2 paper order created.
-- Written once per source paper order; never mutated after creation except
-- shadow_order_id backfill. Purely append-only research data.
CREATE TABLE IF NOT EXISTS classic_shadow_records (
    shadow_id                 TEXT PRIMARY KEY,
    source_signal_id          TEXT NOT NULL,
    source_strategy           TEXT NOT NULL,
    shadow_strategy           TEXT NOT NULL,
    symbol                    TEXT NOT NULL,
    direction                 TEXT NOT NULL,
    signal_time               TEXT NOT NULL,
    decision                  TEXT NOT NULL,      -- PASS | REJECT
    reject_reason             TEXT NOT NULL DEFAULT '',
    shadow_order_id           TEXT,               -- backfilled if PASS+order created
    -- K1 extras
    signal_candle_open        REAL,
    signal_candle_close       REAL,
    signal_candle_change_pct  REAL,
    signal_candle_above_ema20 BOOLEAN,
    break_previous_high       BOOLEAN,
    vol_ratio_15m             REAL,
    -- K2 extras
    range_position_30d        REAL,
    created_at                TEXT NOT NULL DEFAULT ''
);
CREATE INDEX IF NOT EXISTS idx_shadow_source_signal
    ON classic_shadow_records(source_signal_id);
CREATE INDEX IF NOT EXISTS idx_shadow_strategy_time
    ON classic_shadow_records(shadow_strategy, signal_time);
CREATE INDEX IF NOT EXISTS idx_shadow_source_strategy
    ON classic_shadow_records(source_strategy, signal_time);

-- ── Classic C1-C4 scan records ──────────────────────────────────────────────
-- Permanently stores every evaluated coin per cycle, signal or not.
CREATE TABLE IF NOT EXISTS classic_scan_records (
    scan_id         TEXT PRIMARY KEY,
    strategy_id     TEXT NOT NULL,
    scanned_at      TEXT NOT NULL,
    symbol          TEXT NOT NULL,
    pool_type       TEXT NOT NULL,
    pool_rank       INTEGER NOT NULL,
    direction       TEXT NOT NULL,
    change_24h      REAL,
    quote_volume    REAL,
    change_3d       REAL,
    change_7d       REAL,
    range_pos_30d   REAL,
    consec_days     INTEGER,
    trend_4h        TEXT,
    atr_dist_4h     REAL,
    vol_ratio_1h    REAL,
    vol_ratio_15m   REAL,
    vol_grade       TEXT,
    price_pattern   TEXT,
    score           INTEGER NOT NULL DEFAULT 0,
    passed          BOOLEAN NOT NULL DEFAULT FALSE,
    entry           TEXT,
    sl              TEXT,
    tp1             TEXT,
    tp2             TEXT,
    rr              TEXT,
    rejection       TEXT,
    signal_id       TEXT
);
CREATE INDEX IF NOT EXISTS idx_classic_scan_strategy_time
    ON classic_scan_records(strategy_id, scanned_at);
CREATE INDEX IF NOT EXISTS idx_classic_scan_symbol
    ON classic_scan_records(symbol, direction, scanned_at);
CREATE INDEX IF NOT EXISTS idx_classic_scan_signal
    ON classic_scan_records(signal_id) WHERE signal_id IS NOT NULL;
"""


_CONNECT_MAX_ATTEMPTS = 4
_CONNECT_BACKOFF_SECONDS = (0.5, 1.5, 3.0)


def get_conn() -> psycopg2.extensions.connection:
    """Return a new psycopg2 connection. Caller must close/commit.

    Retries transient connection failures (e.g. Neon "Control plane request
    failed" cold-start/control-plane blips) with short backoff before giving
    up, so a single flaky connect doesn't fail an entire scheduled task.
    """
    url = os.environ.get("DATABASE_URL")
    if not url:
        raise RuntimeError("DATABASE_URL is not set — PostgreSQL not configured")

    last_err: Exception | None = None
    for attempt in range(_CONNECT_MAX_ATTEMPTS):
        try:
            return psycopg2.connect(url, connect_timeout=10)
        except psycopg2.OperationalError as exc:
            last_err = exc
            if attempt < _CONNECT_MAX_ATTEMPTS - 1:
                delay = _CONNECT_BACKOFF_SECONDS[attempt]
                log.warning(
                    "[PG] connect attempt %d/%d failed (%s) — retrying in %.1fs",
                    attempt + 1,
                    _CONNECT_MAX_ATTEMPTS,
                    exc,
                    delay,
                )
                time.sleep(delay)
    assert last_err is not None
    raise last_err


_SCORE_COLUMNS: tuple[str, ...] = (
    "ALTER TABLE v3_candidates ADD COLUMN IF NOT EXISTS score_total           INTEGER",
    "ALTER TABLE v3_candidates ADD COLUMN IF NOT EXISTS score_grade           TEXT",
    "ALTER TABLE v3_candidates ADD COLUMN IF NOT EXISTS score_version         TEXT",
    "ALTER TABLE v3_candidates ADD COLUMN IF NOT EXISTS volume_score          INTEGER",
    "ALTER TABLE v3_candidates ADD COLUMN IF NOT EXISTS trend_structure_score INTEGER",
    "ALTER TABLE v3_candidates ADD COLUMN IF NOT EXISTS entry_position_score  INTEGER",
    "ALTER TABLE v3_candidates ADD COLUMN IF NOT EXISTS risk_reward_score     INTEGER",
    "ALTER TABLE v3_candidates ADD COLUMN IF NOT EXISTS strategy_fit_score    INTEGER",
    "ALTER TABLE v3_candidates ADD COLUMN IF NOT EXISTS score_summary         TEXT",
    "ALTER TABLE v3_candidates ADD COLUMN IF NOT EXISTS score_details_json    TEXT",
    "ALTER TABLE v3_candidates ADD COLUMN IF NOT EXISTS scored_at             TEXT",
)


def init_schema() -> None:
    """Create all V3 tables in PostgreSQL (idempotent)."""
    conn = get_conn()
    try:
        with conn.cursor() as cur:
            cur.execute(_PG_DDL)
            for stmt in _SCORE_COLUMNS:
                cur.execute(stmt)
        conn.commit()
        log.info("[PG] V3 schema initialised (including score columns)")
    finally:
        conn.close()
