"""PostgreSQL connection factory and schema initialiser for V3 permanent storage.

All permanent V3 data lives here:
  v3_signal_id_seq   — sequence counter (atomic, locked)
  v3_candidates      — every signal generated by any strategy
  v3_push_queue      — Telegram dispatch queue
  v3_paper_orders    — simulation trade lifecycle
  v3_order_events    — immutable audit log
  v3_feature_store   — raw factors per signal (AI training data)

SQLite keeps only: klines, universe, runner caches.
"""
from __future__ import annotations

import logging
import os

import psycopg2
import psycopg2.extras

log = logging.getLogger(__name__)

_PG_DDL = """
CREATE TABLE IF NOT EXISTS v3_signal_id_seq (
    prefix   TEXT    NOT NULL,
    date     TEXT    NOT NULL,
    next_seq INTEGER NOT NULL DEFAULT 1,
    PRIMARY KEY (prefix, date)
);

CREATE TABLE IF NOT EXISTS v3_candidates (
    signal_id      TEXT PRIMARY KEY,
    strategy_id    TEXT NOT NULL,
    created_at     TEXT NOT NULL,
    symbol         TEXT NOT NULL,
    direction      TEXT NOT NULL,
    entry          TEXT NOT NULL,
    sl             TEXT NOT NULL,
    tp1            TEXT NOT NULL,
    tp2            TEXT,
    rr             TEXT NOT NULL,
    confidence     REAL,
    stop_pct       REAL,
    change_24h     REAL,
    quote_volume   REAL,
    volume_ratio   REAL,
    atr            REAL,
    ema20          REAL,
    ema60          REAL,
    market_regime  TEXT,
    reason         TEXT,
    status         TEXT NOT NULL DEFAULT 'PENDING',
    repeat_count   INTEGER NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_pg_cand_symbol_dir
    ON v3_candidates(symbol, direction, created_at);
CREATE INDEX IF NOT EXISTS idx_pg_cand_strategy
    ON v3_candidates(strategy_id, created_at);
CREATE INDEX IF NOT EXISTS idx_pg_cand_status
    ON v3_candidates(status);

CREATE TABLE IF NOT EXISTS v3_push_queue (
    push_id             TEXT PRIMARY KEY,
    signal_id           TEXT NOT NULL,
    strategy_id         TEXT NOT NULL,
    telegram_message_id TEXT,
    pushed_at           TEXT,
    push_status         TEXT NOT NULL DEFAULT 'QUEUED',
    retry_count         INTEGER NOT NULL DEFAULT 0,
    cooldown_until      TEXT,
    created_at          TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_pg_push_signal
    ON v3_push_queue(signal_id);
CREATE INDEX IF NOT EXISTS idx_pg_push_status
    ON v3_push_queue(push_status, cooldown_until);

CREATE TABLE IF NOT EXISTS v3_paper_orders (
    order_id      TEXT PRIMARY KEY,
    signal_id     TEXT NOT NULL,
    strategy_id   TEXT NOT NULL,
    symbol        TEXT NOT NULL,
    direction     TEXT NOT NULL,
    entry         TEXT NOT NULL,
    stop_loss     TEXT NOT NULL,
    tp1           TEXT NOT NULL,
    tp2           TEXT NOT NULL,
    rr            TEXT NOT NULL,
    status        TEXT NOT NULL DEFAULT 'OPEN',
    result        TEXT,
    created_at    TEXT NOT NULL,
    filled_at     TEXT,
    closed_at     TEXT,
    expires_at    TEXT NOT NULL,
    pnl_pct       TEXT,
    rr_realized   TEXT,
    pushed        INTEGER NOT NULL DEFAULT 1,
    metadata_json TEXT NOT NULL DEFAULT '{}'
);
CREATE INDEX IF NOT EXISTS idx_pg_orders_strategy
    ON v3_paper_orders(strategy_id, status);
CREATE INDEX IF NOT EXISTS idx_pg_orders_symbol
    ON v3_paper_orders(symbol, direction, status);
CREATE INDEX IF NOT EXISTS idx_pg_orders_signal
    ON v3_paper_orders(signal_id);
CREATE INDEX IF NOT EXISTS idx_pg_orders_closed
    ON v3_paper_orders(closed_at);

CREATE TABLE IF NOT EXISTS v3_order_events (
    event_id      TEXT PRIMARY KEY,
    order_id      TEXT NOT NULL,
    signal_id     TEXT NOT NULL,
    event_type    TEXT NOT NULL,
    old_status    TEXT,
    new_status    TEXT,
    candle_high   TEXT,
    candle_low    TEXT,
    triggered_at  TEXT NOT NULL,
    metadata_json TEXT NOT NULL DEFAULT '{}'
);
CREATE INDEX IF NOT EXISTS idx_pg_events_order
    ON v3_order_events(order_id);

CREATE TABLE IF NOT EXISTS v3_feature_store (
    signal_id     TEXT PRIMARY KEY,
    strategy_id   TEXT NOT NULL,
    created_at    TEXT NOT NULL,
    features_json TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_pg_feat_strategy
    ON v3_feature_store(strategy_id, created_at);

CREATE TABLE IF NOT EXISTS live_orders (
    live_order_id   TEXT PRIMARY KEY,
    signal_id       TEXT NOT NULL,
    symbol          TEXT NOT NULL,
    side            TEXT NOT NULL,
    direction       TEXT NOT NULL,
    entry           TEXT NOT NULL,
    sl              TEXT NOT NULL,
    tp              TEXT NOT NULL,
    notional        TEXT NOT NULL,
    leverage        INTEGER NOT NULL DEFAULT 10,
    quantity        TEXT NOT NULL,
    status          TEXT NOT NULL DEFAULT 'PENDING',
    entry_order_id  TEXT,
    sl_order_id     TEXT,
    tp_order_id     TEXT,
    created_at      TEXT NOT NULL,
    updated_at      TEXT NOT NULL,
    reject_reason   TEXT
);
CREATE INDEX IF NOT EXISTS idx_live_orders_status
    ON live_orders(status);
CREATE INDEX IF NOT EXISTS idx_live_orders_symbol
    ON live_orders(symbol, status);
CREATE INDEX IF NOT EXISTS idx_live_orders_signal
    ON live_orders(signal_id);

CREATE TABLE IF NOT EXISTS live_events (
    event_id        TEXT PRIMARY KEY,
    live_order_id   TEXT NOT NULL,
    signal_id       TEXT NOT NULL,
    event_type      TEXT NOT NULL,
    details_json    TEXT NOT NULL DEFAULT '{}',
    created_at      TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_live_events_order
    ON live_events(live_order_id);
CREATE INDEX IF NOT EXISTS idx_live_events_type
    ON live_events(event_type, created_at);
"""


def get_conn() -> psycopg2.extensions.connection:
    """Return a new psycopg2 connection. Caller must close/commit."""
    url = os.environ.get("DATABASE_URL")
    if not url:
        raise RuntimeError("DATABASE_URL is not set — PostgreSQL not configured")
    return psycopg2.connect(url)


def init_schema() -> None:
    """Create all V3 tables in PostgreSQL (idempotent)."""
    conn = get_conn()
    try:
        with conn.cursor() as cur:
            cur.execute(_PG_DDL)
        conn.commit()
        log.info("[PG] V3 schema initialised")
    finally:
        conn.close()
